networks:
  agrotech-network:
    driver: bridge

services:

  # ========================================================
  # ETAPA 1: INFRAESTRUCTURA DE DATOS Y DATOS MAESTROS
  # ========================================================
  roles-permisos:
    build: ./RolesyPermisos
    container_name: ms_roles_permisos
    ports:
      - "8089:8089"
    networks:
      - agrotech-network

  gestor-marca-modelo:
    build: ./GestorMarcaYModelo
    container_name: ms_gestor_marca_modelo
    ports:
      - "8086:8086"
    networks:
      - agrotech-network

  # ========================================================
  # ETAPA 2: CONTROL DE ACCESO Y USUARIOS
  # ========================================================
  gestion-usuario:
    build: ./GestionDeUsuarioNuevo
    container_name: ms_gestion_usuario
    ports:
      - "8081:8081"
    depends_on:
      - roles-permisos
      - gestor-marca-modelo
    networks:
      - agrotech-network

  # ========================================================
  # ETAPA 3: NÚCLEO DEL NEGOCIO (INVENTARIO Y TRANSACCIONES)
  # ========================================================
  gestor-inventario:
    build: ./GestorInventario
    container_name: ms_gestor_inventario
    ports:
      - "8083:8083"
    depends_on:
      - gestion-usuario
    networks:
      - agrotech-network

  gestor-pedidos:
    build: ./GestorPedidos
    container_name: ms_gestor_pedidos
    ports:
      - "8085:8085"
    depends_on:
      - gestion-usuario
    networks:
      - agrotech-network

  gestor-entregas:
    build: ./GestorEntregas
    container_name: ms_gestor_entregas
    ports:
      - "8088:8088"
    depends_on:
      - gestion-usuario
    networks:
      - agrotech-network

  pago-factura:
    build: ./PagoFactura
    container_name: ms_pago_factura
    ports:
      - "8087:8087"
    depends_on:
      - gestion-usuario
    networks:
      - agrotech-network

  # ========================================================
  # ETAPA 4: SERVICIOS DE SOPORTE Y SEGURIDAD PERIMETRAL
  # ========================================================
  soporte-tecnico:
    build: ./SoporteTecnico
    container_name: ms_soporte_tecnico
    ports:
      - "8084:8084"
    depends_on:
      - gestor-inventario
      - gestor-pedidos
      - gestor-entregas
      - pago-factura
    networks:
      - agrotech-network

  autenticacion-nuevo:
    build: ./AutenticacionNuevo
    container_name: ms_autenticacion_nuevo
    ports:
      - "8082:8082"
    depends_on:
      - gestion-usuario
    networks:
      - agrotech-network