spring.application.name=GestorEntregas
server.port=8088

# Conexión con la base de datos de Laragon
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/agrotech_db_gestor_entregas
spring.datasource.username=root
spring.datasource.password=

# Modo de trabajo para JPA
spring.jpa.hibernate.ddl-auto=update

# Logs de SQL estructurados
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto genérico de MySQL (Evita fallas en Hibernate 6+)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Configuración de Swagger / OpenAPI
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Comunicación entre Microservicios (Red interna de Docker)
inventario-service.url=http://ms_gestor_inventario:8083/api/v1
pedidos-service.url=http://ms_gestor_pedidos:8085/api/v1/pedidos
usuarios-service.url=http://ms_gestion_usuario:8081/api/v1/usuarios
usuarios-conectados-service.url=http://ms_autenticacion_nuevo:8082